name: PreCommit

on:
  pull_request:
    branches: [ develop ]
  push:
    branches:
      - '*'

  workflow_dispatch:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
#      - name: Install dependencies for auth
#        run: |
#          python -m pip install --upgrade pip
#          cd auth
#          pip install -r requirements.txt
#          pre-commit install
#      - name: Run pre-commit
#        run: |
#          cd auth
#          mypy . --exclude app/tests
#          flake8 . --exclude app/tests
#        run: cd auth && pre-commit run --show-diff-on-failure --color=always --all-files
